### ISSUE TITLE
Need a new maintainer?

### ISSUE THREAD

**Issue by Boog900** [monero-rs/monero-rs#172]
Hi, this issue is my "application" to a become a maintainer of monero-rs.

I'll start by saying thanks to the current maintainers for all they have done so far, this library was one of my first stepping stones into Monero so im grateful for that!

From what I see it looks like the maintainers of monero-rs are less active lately and I think another maintainer would be beneficial hence I'm asking to be considered for that role.

Thanks!

@h4sh3d @vorot93

**Comment by h4sh3d** [comment]
Hi @Boog900,

Thanks for reaching out! I've been less active lately despite the fact that I love this project(org) and would like to continue maintaining it. This is just because my bandwidth is currently reduced for open source contributions.

I am in favor of accepting new maintainers in this organization.

@vorot93 or @TheCharlatan, if one of you put a thumb up too I can add @Boog900 to the maintainers in the org.

**Comment by h4sh3d** [comment]
I let you close the issue when you're in the team, I've added you at the org level. Thanks for joining the maintainers!

**Comment by Boog900** [comment]
Joined, thank you!
