### ISSUE TITLE
Scanning blockchain for transactions for multiple wallets

### ISSUE THREAD

**Issue by lessless** [monero-rs/monero-rs#72]
Hi,

Are there enough primitives in this library to build an app that can scan the blockchain and pick up transactions for a list of wallets? 
That is the opposite of starting a wallet RPC daemon for every wallet.

**Comment by h4sh3d** [comment]
There is a primitive that recognize outputs and recover the values on a transactions given some keys but the notion of a wallet is not implemented in the library nor the validation of transaction itself.

**Comment by lessless** [comment]
Understood, thank you! That would be enough for my case. The last question - are there any known initiatives to build (maybe a lightweight version of) monero-wallet-rpc with monero-rs?

**Comment by h4sh3d** [comment]
Not that I know

**Comment by lessless** [comment]
Thank you, this clarifies it!

**Comment by thomaseizinger** [comment]
You might be interested in some of the (highly experimental) work that we did here: https://github.com/monero-rs/monero-rs/compare/main...comit-network:main

It includes a pure Rust implementation of the signature algorithms which would be essential to creating a wallet implementation.

There is also some work here where we intended to use this stuff: https://github.com/comit-network/xmr-btc-swap/blob/0c501ba2cc94ed7d6982604ede26d349d115f0e3/monero-wallet/src/lib.rs

Note that this is mostly untested, probably riddled with bugs and you will burn your coins if you use this on mainnet :ok_hand: 

That being said, if you are going to pursue this, there are quite a few tests and I would love for some of this to land in `monero-rs`. We never got around to upstreaming this work because we are blocked on monero supporting pre-signing: https://comit.network/blog/2021/07/02/transaction-presigning

**Comment by lessless** [comment]
@thomaseizinger whoa, amazing stuff!

I'm new to Rust and never dug into Monero protocol deep down before, so please correct me if I'm wrong, but from what I can see the main code related to interacting with the Monero network was moved to https://github.com/comit-network/xmr-btc-swap/blob/master/monero-harness/tests/wallet.rs#L30-L55

It seems that your work has all the necessary primitives to build a wallet in Rust. If you guys will ever consider working on `monero-wallet-rpc` please hit me up, I'd LOVE to contribute. 

Previously I wrote Elixir client for it https://github.com/libra-ventures/monero, so not completely new to the game.

It's just not high enough on my priority list to start immediately by myself but I would really love to see a deamon capable of tracking multiple wallets as it would be hugely beneficial for multisig systems.

Right now, if as a business, I want to use multisig wallets I have to do all kinds of tricks with pooling `monero-wallet-rpc`


Kudos for great work!

**Comment by thomaseizinger** [comment]
> I'm new to Rust and never dug into Monero protocol deep down before, so please correct me if I'm wrong, but from what I can see the main code related to interacting with the Monero network was moved to [comit-network/xmr-btc-swap@`master`/monero-harness/tests/wallet.rs#L30-L55](https://github.com/comit-network/xmr-btc-swap/blob/master/monero-harness/tests/wallet.rs?rgh-link-date=2022-01-06T09%3A56%3A00Z#L30-L55)

What you are looking at there is a test and uses `monero-wallet-rpc` under the hood.

> It seems that your work has all the necessary primitives to build a wallet in Rust. If you guys will ever consider working on `monero-wallet-rpc` please hit me up, I'd LOVE to contribute.

`monero-wallet-rpc` is written in C++ so I am unlikely to ever touch that. I don't trust myself to working in memory-unsafe languages :sweat_smile: 

> It's just not high enough on my priority list to start immediately by myself but I would really love to see a deamon capable of tracking multiple wallets as it would be hugely beneficial for multisig systems.
> 
> Right now, if as a business, I want to use multisig wallets I have to do all kinds of tricks with pooling `monero-wallet-rpc`

If you want to to this in production, I'd recommend to look into creating bindings to https://github.com/monero-ecosystem/monero-cpp in the language of your choice. Alternatively, whilst pooling `monero-wallet-rpc` might be a bit annoying, spawning background processes is a pretty clean abstraction and I am not sure you'd gain much from a wallet with support for multiple wallets. It almost feels like that is quite unnecessary effort on the wallet front when spawning N wallets is a possible alternative. With https://github.com/monero-ecosystem/monero-cpp, you should be able to have N wallets in the same process though so that might improve resilience a bit because you've got less IO.
